server:
  port: 8080

pay-offer:
  token: 2aa7eb8ee69072ec4b07afb468822cc8408e8bc49ae3ebd9

cln:
  grpc:
    host: 127.0.0.1
    port: 9736
    ca-cert: ca.pem
    client-cert: client.pem
    client-key: client-key.pem
